### ISSUE TITLE
search by word still breaks in command line `search.py`

### ISSUE THREAD

**Issue by mangalbhaskar** [hundredblocks/semantic-search#1]
(After, custom model trained for hybrid approach)
* Search By word issues:
1. Error 1:
```bash
Traceback (most recent call last):
  File "search.py", line 90, in <module>
    features, index = index_images(index_folder, features_path, file_mapping, loaded_model)
  File "search.py", line 54, in index_images
    _, _, paths = load_paired_img_wrd(folder, [], use_word_vectors=False)
  File "/home/alpha/Documents/ai-ml-dl/external/semantic-search/utils.py", line 9, in load_paired_img_wrd
    class_names = [fold for fold in os.listdir(folder) if ".DS" not in fold]
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
* Fix: negate the `indexing` flag
```bash
## indexing = image is None ## comment this
indexing = image is not None ## new
```
2. Error 2: after fixing the Error 1:
```bash
Found 400000 word vectors.
Traceback (most recent call last):
  File "search.py", line 112, in <module>
    results = vector_search.search_index_by_value(word_vectors[input_word], image_index, file_mapping)
  File "/home/alpha/Documents/ai-ml-dl/external/semantic-search/vector_search/vector_search.py", line 150, in search_index_by_value
    return [[a, item_mapping[a], distances[1][i]] for i, a in enumerate(distances[0])]
IndexError: string index out of range
```
* Fix: change `file_mapping` to `file_index`
```bash
## results = vector_search.search_index_by_value(word_vectors[input_word], image_index, file_mapping)
results = vector_search.search_index_by_value(word_vectors[input_word], image_index, file_index)
```

Now it works:
* searching for `animal`
```bash
python search.py --input_word animal --features_path custom_features --file_mapping custom_mapping --model_path my_model.hdf5 --glove_path models/glove.6B
```
* results for `animal` search:
```bash
Found 400000 word vectors.
[[200, 'dataset/dog/2008_003852.jpg', 0.9045618176460266], [238, 'dataset/dog/2008_000620.jpg', 0.904861330986023], [244, 'dataset/dog/2008_000897.jpg', 0.9062139391899109], [136, 'dataset/cow/2008_002709.jpg', 0.9222285747528076], [466, 'dataset/sheep/2008_006939.jpg', 0.9265242218971252], [874, 'dataset/cat/2008_006384.jpg', 0.9270879030227661], [223, 'dataset/dog/2008_005563.jpg', 0.9276598691940308], [233, 'dataset/dog/2008_007537.jpg', 0.9289229512214661], [873, 'dataset/cat/2008_005181.jpg', 0.932832658290863], [230, 'dataset/dog/2008_001285.jpg', 0.9330652356147766]]
```
+1 for the very nice implementation and explanation on CBIR. Please fix the above in the main code.

**Comment by mrubash1** [comment]
Thanks so much @mangalbhaskar, this fixes it, and I'll be putting in a PR to fix this!

**Comment by hundredblocks** [comment]
@mrubash1's PR fixing this just got merged, closing the issue! Thank you for reporting @mangalbhaskar
